"""
Env/credential file I/O for the Band submission runtime — reading and writing
backend/.env and backend/agent_config.yaml. Split out of band_runner.py so the
CLI orchestration doesn't mix with file-I/O plumbing.
"""

from __future__ import annotations

import os

import yaml
from dotenv import load_dotenv

_BACKEND_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
_ENV_PATH = os.path.join(_BACKEND_ROOT, ".env")
_AGENT_CONFIG_PATH = os.path.join(_BACKEND_ROOT, "agent_config.yaml")
_REPO_ROOT = os.path.abspath(os.path.join(_BACKEND_ROOT, ".."))
_TRANSCRIPT_OUT = os.path.join(_REPO_ROOT, "web", "public", "transcript.json")


def _load_env() -> None:
    if os.path.exists(_ENV_PATH):
        load_dotenv(_ENV_PATH)


def _user_api_key() -> str:
    _load_env()
    key = os.environ.get("THENVOI_API_KEY", "")
    if not key:
        raise SystemExit("THENVOI_API_KEY not set — see backend/.env.example.")
    return key


def _rest_url() -> str:
    return os.environ.get("THENVOI_REST_URL", "https://app.band.ai")


def _save_agent_config(agents: dict[str, dict]) -> None:
    cfg = {}
    if os.path.exists(_AGENT_CONFIG_PATH):
        with open(_AGENT_CONFIG_PATH) as f:
            cfg = yaml.safe_load(f) or {}
    cfg.setdefault("agents", {})
    for key, data in agents.items():
        cfg["agents"][key] = {
            "agent_id": data["id"],
            "api_key": data["api_key"],
        }
    with open(_AGENT_CONFIG_PATH, "w") as f:
        yaml.dump(cfg, f, default_flow_style=False, sort_keys=False)


def _append_env(env_vars: dict[str, str]) -> None:
    lines = []
    if os.path.exists(_ENV_PATH):
        with open(_ENV_PATH) as f:
            lines = f.readlines()
    updated, out = set(), []
    for line in lines:
        s = line.strip()
        matched = False
        for k, v in env_vars.items():
            if s.startswith(f"{k}=") or s.startswith(f"{k} ="):
                out.append(f"{k}={v}\n")
                updated.add(k)
                matched = True
                break
        if not matched:
            out.append(line)
    remaining = {k: v for k, v in env_vars.items() if k not in updated}
    if remaining:
        if out and out[-1].strip():
            out.append("\n")
        out.append("# Auto-generated by juro.band_runner setup\n")
        for k, v in remaining.items():
            out.append(f"{k}={v}\n")
    with open(_ENV_PATH, "w") as f:
        f.writelines(out)
